version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: ps -ef
      - run: df -h
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: curl ifconfig.io
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
